package com.yupi.yupicturebackend.api.aliyunai.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Min;
import javax.validation.constraints.Max;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.DecimalMax;

/**
 * 图像外绘（Out-Painting）请求实体类
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ImageOutPaintingRequest {

    /**
     * 模型名称（必选）
     * 示例值：image-out-painting
     */
    @NotNull(message = "model 不能为空")
    @JsonProperty("model")
    private String model;

    /**
     * 输入图像的基本信息（必选）
     */
    @NotNull(message = "input 不能为空")
    @JsonProperty("input")
    private Input input;

    /**
     * 输出图像的处理参数（必选）
     */
    @NotNull(message = "parameters 不能为空")
    @JsonProperty("parameters")
    private Parameters parameters;

    /**
     * 输入图像信息内部类
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Input {
        /**
         * 图像 URL 地址或者图像 base64 数据（必选）
         * URL 需为公网可访问的地址，并支持 HTTP 或 HTTPS 协议
         * 图像格式：JPG、JPEG、PNG、HEIF、WEBP
         * 图像大小：不超过 10MB
         * 图像分辨率：不低于 512×512 像素且不超过 4096×4096 像素
         */
        @NotNull(message = "image_url 不能为空")
        @JsonProperty("image_url")
        private String imageUrl;
    }

    /**
     * 处理参数内部类
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Parameters {
        /**
         * 逆时针旋转角度（可选）
         * 默认值为 0，取值范围 [0, 359]，单位为度
         */
        @Min(value = 0, message = "angle 最小值为 0")
        @Max(value = 359, message = "angle 最大值为 359")
        @JsonProperty("angle")
        private Integer angle;

        /**
         * 图像宽高比（可选）
         * 可选值有 ["","1:1", "3:4", "4:3", "9:16", "16:9"]
         * 默认值为 ""，表示不设置输出图像的宽高比
         */
        @JsonProperty("output_ratio")
        private String outputRatio;

        /**
         * 水平方向扩展比例（可选）
         * 默认值为 1.0，取值范围 [1.0, 3.0]
         * 图像居中，在水平方向上按比例扩展图像
         */
        @DecimalMin(value = "1.0", message = "x_scale 最小值为 1.0")
        @DecimalMax(value = "3.0", message = "x_scale 最大值为 3.0")
        @JsonProperty("x_scale")
        private Double xScale;

        /**
         * 垂直方向扩展比例（可选）
         * 默认值为 1.0，取值范围 [1.0, 3.0]
         * 图像居中，在垂直方向上按比例扩展图像
         */
        @DecimalMin(value = "1.0", message = "y_scale 最小值为 1.0")
        @DecimalMax(value = "3.0", message = "y_scale 最大值为 3.0")
        @JsonProperty("y_scale")
        private Double yScale;

        /**
         * 在图像上方添加像素（可选）
         * 默认值为 0
         * 注意：top_offset + bottom_offset < 3×输入图像高度 (需在业务层校验)
         */
        @Min(value = 0, message = "top_offset 不能为负数")
        @JsonProperty("top_offset")
        private Integer topOffset;

        /**
         * 在图像下方添加像素（可选）
         * 默认值为 0
         * 注意：top_offset + bottom_offset < 3×输入图像高度 (需在业务层校验)
         */
        @Min(value = 0, message = "bottom_offset 不能为负数")
        @JsonProperty("bottom_offset")
        private Integer bottomOffset;

        /**
         * 在图像左侧添加像素（可选）
         * 默认值为 0
         * 注意：left_offset + right_offset < 3×输入图像宽度 (需在业务层校验)
         */
        @Min(value = 0, message = "left_offset 不能为负数")
        @JsonProperty("left_offset")
        private Integer leftOffset;

        /**
         * 在图像右侧添加像素（可选）
         * 默认值为 0
         * 注意：left_offset + right_offset < 3×输入图像宽度 (需在业务层校验)
         */
        @Min(value = 0, message = "right_offset 不能为负数")
        @JsonProperty("right_offset")
        private Integer rightOffset;

        /**
         * 开启图像最佳质量模式（可选）
         * 默认值为 false，减少图像生成的等待时间
         * 如果设置为 true，耗时会成倍增加
         */
        @JsonProperty("best_quality")
        private Boolean bestQuality;

        /**
         * 限制模型生成的图像文件大小（可选）
         * 默认值为 true
         * 当输入图像单边长度<=10000 时，输出图像文件大小在 5MB 以下
         * 建议设置为 true
         */
        @JsonProperty("limit_image_size")
        private Boolean limitImageSize;

        /**
         * 添加 Generated by AI 水印（可选）
         * 默认值为 True，在输出图像左下角处添加水印
         */
        @JsonProperty("add_watermark")
        private Boolean addWatermark;
    }
}

